/** Plain-English explanations for each metric key */
export const METRIC_EXPLANATIONS: Record<string, string> = {
  spend: 'Total amount spent on ads across this platform',
  impressions: 'Number of times your ads or posts were displayed',
  organic_impressions: 'Times your unpaid content was shown to people',
  paid_impressions: 'Times your paid ads were shown to people',
  clicks: 'Total number of clicks on your ads or content',
  link_clicks: 'Clicks that took people to your website or landing page',
  organic_clicks: 'Clicks on your unpaid content',
  ctr: 'Percentage of people who clicked after seeing your content',
  conversions: 'Actions people took after clicking (purchases, sign-ups, etc.)',
  conversions_value: 'Total monetary value of all conversions',
  conversion_rate: 'Percentage of clicks that resulted in a conversion',
  cpc: 'Average cost for each click on your ads',
  cpm: 'Cost per 1,000 times your ad was shown',
  cost_per_conversion: 'Average cost to achieve one conversion',
  cost_per_lead: 'Average cost to acquire one lead',
  roas: 'Revenue generated for every pound spent on ads',
  reach: 'Unique people who saw your content — includes both organic and paid reach',
  frequency: 'Average number of times each person saw your ad',
  search_impression_share: 'Percentage of available search impressions you captured',
  leads: 'Number of potential customers who submitted their details',
  total_followers: 'Current total number of followers on this platform',
  follower_growth: 'New followers gained during this period',
  follower_removes: 'People who unfollowed during this period',
  audience_growth_rate: 'Percentage growth of your audience',
  page_likes: 'Total likes on your Facebook Page',
  page_views: 'Number of times your page was viewed',
  profile_visits: 'Number of visits to your profile',
  engagement: 'Total interactions (likes, comments, shares, saves)',
  engagement_rate: 'Percentage of people who interacted with your content',
  likes: 'Number of likes on your posts',
  comments: 'Number of comments on your posts',
  shares: 'Number of times your content was shared',
  saves: 'Number of times people saved your content',
  reactions: 'Total reactions (likes, love, wow, etc.) on your posts',
  video_views: 'Total organic video views across your social platforms',
  average_watch_time: 'Average time people spent watching your videos',
  posts_published: 'Number of posts you published',
  reel_count: 'Number of Reels published',
  image_count: 'Number of image posts published',
  carousel_count: 'Number of carousel posts published',
  website_clicks: 'Clicks to your website from your profile',
  email_contacts: 'Number of email taps from your profile',
  media_count: 'Total number of posts on your profile',
  // Google Search Console
  search_clicks: 'Number of clicks from Google search results to your website',
  search_impressions: 'Number of times your site appeared in Google search results',
  search_ctr: 'Percentage of search impressions that resulted in a click',
  search_position: 'Average ranking position of your pages in Google search results',
  top_queries: 'Search terms people used to find your website',
  gsc_top_pages: 'Pages on your site that received the most search traffic',
  // Google Analytics
  sessions: 'Total number of visits to your website',
  active_users: 'Number of unique users who engaged with your site',
  new_users: 'First-time visitors to your website during this period',
  ga_page_views: 'Total number of pages viewed on your website',
  bounce_rate: 'Percentage of visitors who left after viewing only one page',
  avg_session_duration: 'Average time a visitor spends on your website per visit',
  pages_per_session: 'Average number of pages viewed per visit',
  traffic_sources: 'Where your website traffic comes from (search, social, direct, etc.)',
  // Google Business Profile
  gbp_views: 'Number of times your Google Business Profile was viewed',
  gbp_searches: 'Number of times your business appeared in Google Search or Maps',
  gbp_calls: 'Number of phone calls made from your Google Business Profile',
  gbp_direction_requests: 'Number of times people requested directions to your business',
  gbp_website_clicks: 'Number of clicks to your website from your Google Business Profile',
  gbp_reviews_count: 'Total number of reviews on your Google Business Profile',
  gbp_average_rating: 'Average star rating of your Google Business Profile reviews',
  gbp_conversations: 'Messages and conversations initiated through your Google Business Profile',
  gbp_bookings: 'Bookings made through your Google Business Profile',
  gbp_new_reviews: 'New reviews received on your Google Business Profile during this period',
  gbp_maps_desktop: 'Times your business appeared on Google Maps on desktop',
  gbp_maps_mobile: 'Times your business appeared on Google Maps on mobile',
  gbp_search_desktop: 'Times your business appeared in Google Search on desktop',
  gbp_search_mobile: 'Times your business appeared in Google Search on mobile',
  // YouTube
  subscribers: 'Net new subscribers gained during this period',
  views: 'Organic views — times your content was seen excluding paid/boosted delivery',
  watch_time: 'Total minutes people spent watching your videos',
  videos_published: 'Total number of videos on your channel',
  avg_view_duration: 'Average time in seconds viewers watched your videos',
  top_videos: 'Your best-performing videos during this period',
  new_followers:  'New accounts that followed your page this period',
  cta_clicks:     'Clicks on your page contact info and call-to-action button',
  post_views:     'Total views across all your posts this period',
  post_clicks:    'Total clicks across all your posts this period',
  engaged_users:  'Unique people who interacted with your post',
  reaction_like:  'Number of Like reactions',
  reaction_love:  'Number of Love reactions',
  reaction_wow:   'Number of Wow reactions',
  reaction_haha:  'Number of Haha reactions',
  reaction_sorry: 'Number of Sorry reactions',
  reaction_anger: 'Number of Angry reactions',
  // Pinterest
  pin_clicks: 'Clicks on your pins that take people to on-Pinterest or off-Pinterest destinations',
  outbound_clicks: 'Clicks that take people off Pinterest to your website or landing page',
  total_pins: 'Total number of pins on your Pinterest profile',
  total_boards: 'Total number of boards on your Pinterest profile',
  top_boards: 'Your boards with the most pins',
};

/** Timezone options for client configuration */
export const TIMEZONE_OPTIONS = [
  { value: 'Europe/London', label: 'London (GMT/BST)' },
  { value: 'Europe/Dublin', label: 'Dublin (GMT/IST)' },
  { value: 'Europe/Paris', label: 'Paris (CET/CEST)' },
  { value: 'Europe/Berlin', label: 'Berlin (CET/CEST)' },
  { value: 'Europe/Amsterdam', label: 'Amsterdam (CET/CEST)' },
  { value: 'Europe/Madrid', label: 'Madrid (CET/CEST)' },
  { value: 'Europe/Rome', label: 'Rome (CET/CEST)' },
  { value: 'Europe/Warsaw', label: 'Warsaw (CET/CEST)' },
  { value: 'Europe/Lisbon', label: 'Lisbon (WET/WEST)' },
  { value: 'Europe/Athens', label: 'Athens (EET/EEST)' },
  { value: 'America/New_York', label: 'New York (EST/EDT)' },
  { value: 'America/Chicago', label: 'Chicago (CST/CDT)' },
  { value: 'America/Denver', label: 'Denver (MST/MDT)' },
  { value: 'America/Los_Angeles', label: 'Los Angeles (PST/PDT)' },
  { value: 'America/Toronto', label: 'Toronto (EST/EDT)' },
  { value: 'America/Vancouver', label: 'Vancouver (PST/PDT)' },
  { value: 'Pacific/Auckland', label: 'Auckland (NZST/NZDT)' },
  { value: 'Australia/Sydney', label: 'Sydney (AEST/AEDT)' },
  { value: 'Australia/Melbourne', label: 'Melbourne (AEST/AEDT)' },
  { value: 'Asia/Dubai', label: 'Dubai (GST)' },
  { value: 'Asia/Singapore', label: 'Singapore (SGT)' },
  { value: 'Asia/Tokyo', label: 'Tokyo (JST)' },
];
