/** Plain-English explanations for each metric key */
export const METRIC_EXPLANATIONS: Record<string, string> = {
  spend: 'Total amount spent on ads across this platform',
  impressions: 'Number of times your ads or posts were displayed',
  organic_impressions: 'Times your unpaid content was shown to people',
  paid_impressions: 'Times your paid ads were shown to people',
  clicks: 'Total number of clicks on your ads or content',
  link_clicks: 'Clicks that took people to your website or landing page',
  organic_clicks: 'Clicks on your unpaid content',
  ctr: 'Percentage of people who clicked after seeing your content',
  conversions: 'Actions people took after clicking (purchases, sign-ups, etc.)',
  conversions_value: 'Total monetary value of all conversions',
  conversion_rate: 'Percentage of clicks that resulted in a conversion',
  cpc: 'Average cost for each click on your ads',
  cpm: 'Cost per 1,000 times your ad was shown',
  cost_per_conversion: 'Average cost to achieve one conversion',
  roas: 'Revenue generated for every pound spent on ads',
  reach: 'Number of unique people who saw your content',
  frequency: 'Average number of times each person saw your ad',
  search_impression_share: 'Percentage of available search impressions you captured',
  leads: 'Number of potential customers who submitted their details',
  total_followers: 'Current total number of followers on this platform',
  follower_growth: 'New followers gained during this period',
  follower_removes: 'People who unfollowed during this period',
  audience_growth_rate: 'Percentage growth of your audience',
  page_likes: 'Total likes on your Facebook Page',
  page_views: 'Number of times your page was viewed',
  profile_visits: 'Number of visits to your profile',
  engagement: 'Total interactions (likes, comments, shares, saves)',
  engagement_rate: 'Percentage of people who interacted with your content',
  likes: 'Number of likes on your posts',
  comments: 'Number of comments on your posts',
  shares: 'Number of times your content was shared',
  saves: 'Number of times people saved your content',
  reactions: 'Total reactions (likes, love, wow, etc.) on your posts',
  video_views: 'Number of times your videos were watched',
  average_watch_time: 'Average time people spent watching your videos',
  posts_published: 'Number of posts you published',
  reel_count: 'Number of Reels published',
  image_count: 'Number of image posts published',
  carousel_count: 'Number of carousel posts published',
  website_clicks: 'Clicks to your website from your profile',
  email_contacts: 'Number of email taps from your profile',
  media_count: 'Total number of posts on your profile',
};

/** Timezone options for client configuration */
export const TIMEZONE_OPTIONS = [
  { value: 'Europe/London', label: 'London (GMT/BST)' },
  { value: 'Europe/Dublin', label: 'Dublin (GMT/IST)' },
  { value: 'Europe/Paris', label: 'Paris (CET/CEST)' },
  { value: 'Europe/Berlin', label: 'Berlin (CET/CEST)' },
  { value: 'Europe/Amsterdam', label: 'Amsterdam (CET/CEST)' },
  { value: 'Europe/Madrid', label: 'Madrid (CET/CEST)' },
  { value: 'Europe/Rome', label: 'Rome (CET/CEST)' },
  { value: 'Europe/Warsaw', label: 'Warsaw (CET/CEST)' },
  { value: 'Europe/Lisbon', label: 'Lisbon (WET/WEST)' },
  { value: 'Europe/Athens', label: 'Athens (EET/EEST)' },
  { value: 'America/New_York', label: 'New York (EST/EDT)' },
  { value: 'America/Chicago', label: 'Chicago (CST/CDT)' },
  { value: 'America/Denver', label: 'Denver (MST/MDT)' },
  { value: 'America/Los_Angeles', label: 'Los Angeles (PST/PDT)' },
  { value: 'America/Toronto', label: 'Toronto (EST/EDT)' },
  { value: 'America/Vancouver', label: 'Vancouver (PST/PDT)' },
  { value: 'Pacific/Auckland', label: 'Auckland (NZST/NZDT)' },
  { value: 'Australia/Sydney', label: 'Sydney (AEST/AEDT)' },
  { value: 'Australia/Melbourne', label: 'Melbourne (AEST/AEDT)' },
  { value: 'Asia/Dubai', label: 'Dubai (GST)' },
  { value: 'Asia/Singapore', label: 'Singapore (SGT)' },
  { value: 'Asia/Tokyo', label: 'Tokyo (JST)' },
];
